#!/usr/bin/env python

# Based on libgpod examples.

import os.path
import sys
import gpod
from optparse import OptionParser

parser = OptionParser(usage="usage: %prog [options]",
                      description="Delete music and playlist from your ipod.",
                      epilog="Files are read from stdin, one per line.")
parser.add_option("-m", "--mountpoint", dest="mountpoint",
                  default="/mnt/ipod",
                  help="use iPod at MOUNTPOINT", metavar="MOUNTPOINT")
parser.add_option("-l", "--playlist", dest="playlist",
                  help="delete PLAYLIST (but not its track)",
                  metavar="PLAYLIST")
(options, args) = parser.parse_args()

db = gpod.Database(options.mountpoint)

if options.playlist:
    try:
        chosen_playlist = int(options.playlist)
    except ValueError:
        chosen_playlist = options.playlist

    playlist = None
    for pl in db.Playlists:
        if pl.name == chosen_playlist:
            playlist = pl
    if not playlist:
        raise ValueError("playlist %r not found." % (chosen_playlist,))
    else:
        db.remove(playlist)

_filenames = set()
for f in sys.stdin.readlines():
    if f[-1] == '\n':
        f = f[:-1]
    if os.path.isfile(f):
        _filenames.add(f)

for track in db:
    try:
        f = track["userdata"]["filename_utf8"]
    except KeyError:
        continue

    if f not in _filenames:
        continue

    print ("T: "
           "%r %r %r %r "
           "%d %d %r") % (
        f, track["artist"], track["album"], track["genre"],
        track["tracklen"], track["track_nr"], track["title"])
    db.remove(track)

db.close()
